//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsSoft.Orthography.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsSoft.Orthography.Properties.ResourcesRu", typeof(ResourcesRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to штука,штуки,штук.
        /// </summary>
        internal static string AmmontUnit_Pluralize_Case1 {
            get {
                return ResourceManager.GetString("AmmontUnit_Pluralize_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллиард,миллиарда,миллиардов.
        /// </summary>
        internal static string Billion_Pluralize_Case1 {
            get {
                return ResourceManager.GetString("Billion_Pluralize_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to копейка,копейки,копеек.
        /// </summary>
        internal static string CurrencyRuCent_Pluralize_Case1 {
            get {
                return ResourceManager.GetString("CurrencyRuCent_Pluralize_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рубль,рубля,рублей.
        /// </summary>
        internal static string CurrencyRuUnit_Pluralize_Case1 {
            get {
                return ResourceManager.GetString("CurrencyRuUnit_Pluralize_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сто,двести,триста,четыреста,пятьсот,шестьсот,семьсот,восемьсот,девятьсот.
        /// </summary>
        internal static string Hundreds_Case1 {
            get {
                return ResourceManager.GetString("Hundreds_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to миллион,миллиона,миллионов.
        /// </summary>
        internal static string Million_Pluralize_Case1 {
            get {
                return ResourceManager.GetString("Million_Pluralize_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to десять,двадцать,тридцать,сорок,пятьдесят,шестьдесят,семьдесят,восемьдесят,девяносто.
        /// </summary>
        internal static string Tens_Case1 {
            get {
                return ResourceManager.GetString("Tens_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тысяча,тысячи,тысяч.
        /// </summary>
        internal static string Thousand_Pluralize_Case1 {
            get {
                return ResourceManager.GetString("Thousand_Pluralize_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to триллион,триллиона,триллионов.
        /// </summary>
        internal static string Trillion_Pluralize_Case1 {
            get {
                return ResourceManager.GetString("Trillion_Pluralize_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одиннадцать,двенадцать,тринадцать,четырнадцать,пятнадцать,шестнадцать,семнадцать,восемнадцать,девятнадцать.
        /// </summary>
        internal static string Twenties_Case1 {
            get {
                return ResourceManager.GetString("Twenties_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ноль,один,два,три,четыре,пять,шесть,семь,восемь,девять.
        /// </summary>
        internal static string Units_Case1 {
            get {
                return ResourceManager.GetString("Units_Case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ноль,одна,две,три,четыре,пять,шесть,семь,восемь,девять.
        /// </summary>
        internal static string UnitsFemale_Case1 {
            get {
                return ResourceManager.GetString("UnitsFemale_Case1", resourceCulture);
            }
        }
    }
}
