//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsSoft.Orthography.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsSoft.Orthography.Properties.ResourcesEn", typeof(ResourcesEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cent,cents,cents.
        /// </summary>
        internal static string CurrencyEnCent_Pluralize {
            get {
                return ResourceManager.GetString("CurrencyEnCent_Pluralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dollar,dollars,dollars.
        /// </summary>
        internal static string CurrencyEnUnit_Pluralize {
            get {
                return ResourceManager.GetString("CurrencyEnUnit_Pluralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero,one,two,three,four,five,six,seven,eight,nine.
        /// </summary>
        internal static string Ones {
            get {
                return ResourceManager.GetString("Ones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ten,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen.
        /// </summary>
        internal static string Teens {
            get {
                return ResourceManager.GetString("Teens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ,ten,twenty,thirty,forty,fifty,sixty,seventy,eighty,ninety.
        /// </summary>
        internal static string Tens {
            get {
                return ResourceManager.GetString("Tens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ,thousand,million,billion,trillion,quadrillion.
        /// </summary>
        internal static string Thousands {
            get {
                return ResourceManager.GetString("Thousands", resourceCulture);
            }
        }
    }
}
